export * from './detail-basic-info';
export * from './detail-request-tab';
export * from './detail-schedules-tab';
export * from './update-general-tab';
export * from './update-measurement-tab';
export * from './update-media-tab';
export * from './update-salary-tab';
export * from './update-comcard-tab';
export * from './update-image-tab';
